(load "./lisp/util.lisp")
(load "./lisp/data.lisp")
(load "./lisp/name.lisp")
(load "./lisp/action.lisp")
(load "./lisp/state.lisp")
(load "./lisp/load.lisp")
(load "./lisp/building.lisp")
(load "./lisp/play.lisp")
